config/routes.rb
Rails.application.routes.draw do
  resources :interests
  resources :devices
  resources :groups
  resources :dashboards
  resources :admin_dashboards
  resources :ratings
  resources :homeworks
  resources :school_categories
  resources :quizzes
  resources :answers
  resources :questions
  resources :courses
  resources :follows
  resources :money_categories
  resources :categories
  resources :products
  resources :carts
  resources :cards
  resources :matches
  resources :message
  resources :likes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',           # Custom sessions controller
    registrations: 'users/registrations' # Custom registrations controller
    # Add other Devise controllers you've customized
  }

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/interest.rb
class Interest < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :question
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :likes
  has_many :matches
  has_many :messages
  has_many :cards
  has_one :cart
  has_many :follows
  has_many :posts
  has_many :quizzes
  has_many :courses
  has_many :homework
  has_many :interests
  has_many :ratings
  belongs_to :group
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy!

    respond_to do |format|
      format.html { redirect_to answers_url, notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:answer, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <p>
    <strong>Answer:</strong>
    <%= answer.answer %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= answer.question_id %>
  </p>

</div>

app/views/answers/_form.html.erb
<%= form_with(model: answer) do |form| %>
  <% if answer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.text_area :answer %>
  </div>

  <div>
    <%= form.label :question_id, style: "display: block" %>
    <%= form.text_field :question_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Show this answer", @answer %> |
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Answers</h1>

<div id="answers">
  <% @answers.each do |answer| %>
    <%= render answer %>
    <p>
      <%= link_to "Show this answer", answer %>
    </p>
  <% end %>
</div>

<%= link_to "New answer", new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @answer %>

<div>
  <%= link_to "Edit this answer", edit_answer_path(@answer) %> |
  <%= link_to "Back to answers", answers_path %>

  <%= button_to "Destroy this answer", @answer, method: :delete %>
</div>