config/routes.rb
Rails.application.routes.draw do
  resources :interests
  resources :devices
  resources :groups
  resources :dashboards
  resources :admin_dashboards
  resources :ratings
  resources :homeworks
  resources :school_categories
  resources :quizzes
  resources :answers
  resources :questions
  resources :courses
  resources :follows
  resources :money_categories
  resources :categories
  resources :products
  resources :carts
  resources :cards
  resources :matches
  resources :message
  resources :likes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',           # Custom sessions controller
    registrations: 'users/registrations' # Custom registrations controller
    # Add other Devise controllers you've customized
  }

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/interest.rb
class Interest < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :question
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :likes
  has_many :matches
  has_many :messages
  has_many :cards
  has_one :cart
  has_many :follows
  has_many :posts
  has_many :quizzes
  has_many :courses
  has_many :homework
  has_many :interests
  has_many :ratings
  belongs_to :group
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy!

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:to, :from)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :to, style: "display: block" %>
    <%= form.number_field :to %>
  </div>

  <div>
    <%= form.label :from, style: "display: block" %>
    <%= form.number_field :from %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <p>
    <strong>To:</strong>
    <%= match.to %>
  </p>

  <p>
    <strong>From:</strong>
    <%= match.from %>
  </p>

</div>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Matches</h1>

<div id="matches">
  <% @matches.each do |match| %>
    <%= render match %>
    <p>
      <%= link_to "Show this match", match %>
    </p>
  <% end %>
</div>

<%= link_to "New match", new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match %>

<div>
  <%= link_to "Edit this match", edit_match_path(@match) %> |
  <%= link_to "Back to matches", matches_path %>

  <%= button_to "Destroy this match", @match, method: :delete %>
</div>